import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Flame,Bell,Check,Plus}from'lucide-react';import'./style.css';
const K='daytracker.v2';
const key=d=>d.toLocaleDateString('en-CA'),day=()=>key(new Date());
const START_DAYS={'2026-09-25':1,'2026-09-26':1,'2026-09-27':1,'2026-09-28':1,'2026-09-29':1,'2026-09-30':1,'2026-10-01':1,'2026-10-02':1,'2026-10-03':1};
const START={days:START_DAYS,best:9,postOffset:2,seeded:true};
function load(){try{let v=JSON.parse(localStorage.getItem(K));if(v)return v;let old=JSON.parse(localStorage.getItem('daytracker.v1'));if(old&&Object.keys(old.days||{}).length){return{...old,postOffset:0,seeded:true}}return structuredClone(START)}catch{return structuredClone(START)}}
function calc(s){let n=0,d=new Date();while((s.days[key(d)]||0)>0){n++;d.setDate(d.getDate()-1)}return n}
function App(){const[s,setS]=useState(load);const[now,setNow]=useState(new Date());useEffect(()=>{let i=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(i)},[]);useEffect(()=>localStorage.setItem(K,JSON.stringify(s)),[s]);let today=s.days[day()]||0,streak=calc(s),total=Object.values(s.days).reduce((a,b)=>a+b,0)+(s.postOffset||0);let end=new Date(now);end.setHours(24,0,0,0);let ms=end-now,h=Math.floor(ms/36e5),m=Math.floor(ms%36e5/6e4),sec=Math.floor(ms%6e4/1000);const week=useMemo(()=>Array.from({length:7},(_,i)=>{let d=new Date();d.setDate(d.getDate()-(6-i));let k=key(d);return{label:d.toLocaleDateString('en-US',{weekday:'narrow'}),done:(s.days[k]||0)>0,today:k===day()}}),[s,now.getDate()]);
function post(){setS(x=>{let z=structuredClone(x);z.days[day()]=(z.days[day()]||0)+1;z.best=Math.max(z.best||0,calc(z));return z});navigator.vibrate?.(35)}
async function notify(){if(!('Notification'in window))return;let p=await Notification.requestPermission();if(p==='granted')new Notification('DayTracker',{body:'Reminders enabled. Keep the streak alive.'})}
return <main><div className="orb o1"/><div className="orb o2"/><section className="shell"><header><div><span className="eyebrow">DAILY CONSISTENCY</span><h1>DayTracker</h1></div><button className="icon" onClick={notify} aria-label="Enable reminders"><Bell size={19}/></button></header><div className="hero"><div className="fire"><Flame size={22} fill="currentColor"/></div><div className="number">{streak}</div><div className="days">DAY{streak===1?'':'S'} STRONG</div><p>{today?'You showed up today.':'Keep the streak alive.'}</p></div><button className={'post '+(today?'done':'')} onClick={post}>{today?<><Plus/>POSTED +1 <span>{today}× TODAY</span></>:<><Plus/>I POSTED TODAY</>}</button><div className="stats"><div><span>BEST</span><b>{Math.max(s.best||0,streak)} days</b></div><i/><div><span>TOTAL POSTS</span><b>{total}</b></div></div><div className="week">{week.map((x,i)=><div key={i}><span>{x.label}</span><i className={(x.done?'hit ':'')+(x.today?'current':'')}>{x.done&&<Check size={13}/>}</i></div>)}</div><footer><span>RESET WINDOW</span><b>{h}h {String(m).padStart(2,'0')}m {String(sec).padStart(2,'0')}s</b><small>until midnight</small></footer></section></main>}
createRoot(document.getElementById('root')).render(<App/>);
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));